### ISSUE TITLE
Add ChakraCore to lib/exe names

### ISSUE THREAD

**Issue by akrantz** [kfarnung/ChakraCore-Debugger#57]
In order to make it clearer that the files are related to ChakraCore, let's add ChakraCore to the name.

Consider renaming from:

Debug.Protocol.lib
Debug.ProtocolHandler.lib
Debug.Sample.exe

to:

ChakraCore.DebugProtocol.lib
ChakraCore.DebugProtocolHandler.lib
ChakraCore.DebugSample.exe

**Comment by kfarnung** [comment]
That seems fine. Feel free to open a PR.

**Comment by akrantz** [comment]
I have this change: https://github.com/akrantz/ChakraCore-Debugger/commit/e46d3cb2c17880f53259bc3dfd212bef7e1fc4f0.

I need pull request https://github.com/kfarnung/ChakraCore-Debugger/pull/56 to be made first, as the other changes to the project would come after.

**Comment by akrantz** [comment]
I moved the build output into a subdir of "\build\bin" and "\build\obj". This is somewhat analogous to CharkaCore using "Build\VCBuild\bin" and obj.

**Comment by kfarnung** [comment]
I think I can make this a much simpler change, actually, I should have a PR soon.
